import type { Language } from './i18n'

export type Country = {
  name: string
  code: string
  language: Language
  currency: string
  group: string
  regions: string[]
  headerRegions: string[]
  flagUrl: string
}

// Supported interface languages: Unicode CLDR 48 territoryInfo and currencyData.
// Include national/de facto languages or languages used by at least 20% of residents.
// Iceland: English is widely used (visiticeland.com/article/icelandic-language/).
// Multilingual countries default to the most-used supported national language.
const countryData: Omit<Country, 'flagUrl'>[] = [
  {"name":"Latvija","code":"lv","language":"LV","currency":"EUR","group":"Baltija","regions":["Rīga un rajons","Jūrmala","Pierīga","Vidzeme","Kurzeme","Zemgale","Latgale"],"headerRegions":["Rīga","Jūrmala","Pierīga","Kurzeme","Vidzeme","Zemgale","Latgale","Liepāja","Daugavpils","Ventspils","Jelgava","Valmiera","Ogre"]},
  {"name":"Alžīrija","code":"dz","language":"FR","currency":"DZD","group":"","regions":[],"headerRegions":[]},
  {"name":"Andora","code":"ad","language":"ES","currency":"EUR","group":"","regions":[],"headerRegions":[]},
  {"name":"Angola","code":"ao","language":"PT","currency":"AOA","group":"","regions":[],"headerRegions":[]},
  {"name":"Antigva un Barbuda","code":"ag","language":"EN","currency":"XCD","group":"","regions":[],"headerRegions":[]},
  {"name":"Apvienotie Arābu Emirāti","code":"ae","language":"EN","currency":"AED","group":"Tuvie Austrumi","regions":["Dubaija","Abū Dabī","Šardža"],"headerRegions":["Dubaija","Abudabi","Šārdža","Adžmana","Raselhaima"]},
  {"name":"Argentīna","code":"ar","language":"ES","currency":"ARS","group":"Dienvidamerika","regions":["Buenosairesa","Kordoba","Mendosa","Rosario","Santa Fe"],"headerRegions":["Buenosairesa","Kordoba","Mendosa","Rosario","Santa Fe"]},
  {"name":"Armēnija","code":"am","language":"RU","currency":"AMD","group":"","regions":[],"headerRegions":[]},
  {"name":"ASV","code":"us","language":"EN","currency":"USD","group":"Ziemeļamerika","regions":["Alabama","Aļaska (Alaska)","Arizona","Arkanzasa (Arkansas)","Kalifornija (California)","Kolorādo","Konektikuta (Connecticut)","Delavēra (Delaware)","Florida","Džordžija (Georgia)","Havajas (Hawaii)","Aidaho (Idaho)","Ilinoisa (Illinois)","Indiana","Aiovas (Iowa)","Kanzasa (Kansas)","Kentuki (Kentucky)","Luiziāna (Louisiana)","Meina (Maine)","Merilenda (Maryland)","Masačūsetsa (Massachusetts)","Mičigana (Michigan)","Minesota (Minnesota)","Misisipi (Mississippi)","Misūri (Missouri)","Montāna (Montana)","Nebraska","Nevada","Ņūhempšīra (New Hampshire)","Ņūdžersija (New Jersey)","Ņūmeksika (New Mexico)","Ņujorka (New York)","Ziemeļkarolīna (North Carolina)","Ziemeļdakota (North Dakota)","Ohaio (Ohio)","Oklahoma","Oregonas (Oregon)","Pensilvānija (Pennsylvania)","Roudailenda (Rhode Island)","Dienvidkarolīna (South Carolina)","Dienviddakota (South Dakota)","Tenesī (Tennessee)","Teksasa (Texas)","Jūta (Utah)","Vermonta (Vermont)","Virdžīnija (Virginia)","Vašingtona (Washington)","Rietumvirdžīnija (West Virginia)","Viskonsina (Wisconsin)","Vaiominga (Wyoming)"],"headerRegions":["Alabama (AL)","Aļaska (AK)","Arizona (AZ)","Arkanzasa (AR)","Kalifornija (CA)","Kolorādo (CO)","Konektikuta (CT)","Delavēra (DE)","Florida (FL)","Džordžija (GA)","Havajas (HI)","Aidaho (ID)","Ilinoisa (IL)","Indianāna (IN)","Aiova (IA)","Kanzasa (KS)","Kentuki (KY)","Luiziāna (LA)","Meina (ME)","Merilenda (MD)"," Masačūsetsa (MA)","Mičigana (MI)","Minesota (MN)","Misisipi (MS)","Misūri (MO)","Montāna (MT)","Nebraska (NE)","Nevada (NV)","Ņūhempšīra (NH)","Ņūdžersija (NJ)","Ņūmexika (NM)","Ņujorka (NY)","Ziemeļkarolīna (NC)","Ziemeļdakota (ND)","Ohaio (OH)","Oklahoma (OK)","Oregonas štats (OR)","Pensilvānija (PA)","Roda Ailenda (RI)","Dienvidkarolīna (SC)","Dienviddakota (SD)","Tenesī (TN)","Teksasa (TX)","Jūta (UT)","Vermonta (VT)","Virdžīnija (VA)","Vašingtona (WA)","Rietumvirdžīnija (WV)","Viskonsina (WI)","Vaiominga (WY)"]},
  {"name":"Austrālija","code":"au","language":"EN","currency":"AUD","group":"Okeānija","regions":["Sidneja","Melburna","Brisbena","Pērta","Adelaida"],"headerRegions":["Sidneja","Melburna","Brisbena","Pērta","Jaundienvidvelsa","Viktorija","Kvīnslenda"]},
  {"name":"Austrija","code":"at","language":"DE","currency":"EUR","group":"Eiropa","regions":["Vīne","Zalcburga","Grāca","Linca","Tiroli","Forarlberga","Kārtene"],"headerRegions":["Vīne","Zalcburga","Grāca","Linca","Tiroli","Forarlberga","Kārtene"]},
  {"name":"Austrumtimora","code":"tl","language":"PT","currency":"USD","group":"","regions":[],"headerRegions":[]},
  {"name":"Bahamu salas","code":"bs","language":"EN","currency":"BSD","group":"","regions":[],"headerRegions":[]},
  {"name":"Baltkrievija","code":"by","language":"RU","currency":"BYN","group":"","regions":[],"headerRegions":[]},
  {"name":"Barbadosa","code":"bb","language":"EN","currency":"BBD","group":"","regions":[],"headerRegions":[]},
  {"name":"Beliza","code":"bz","language":"EN","currency":"BZD","group":"","regions":[],"headerRegions":[]},
  {"name":"Beļģija","code":"be","language":"NL","currency":"EUR","group":"Eiropa","regions":["Brusese","Antverpene","Gente","Flandrija","Valonija","Lježa"],"headerRegions":["Brusese","Antverpene","Gente","Flandrija","Valonija","Lježa"]},
  {"name":"Benina","code":"bj","language":"FR","currency":"XOF","group":"","regions":[],"headerRegions":[]},
  {"name":"Bolīvija","code":"bo","language":"ES","currency":"BOB","group":"","regions":[],"headerRegions":[]},
  {"name":"Bosnija un Hercegovina","code":"ba","language":"EN","currency":"BAM","group":"","regions":[],"headerRegions":[]},
  {"name":"Botsvāna","code":"bw","language":"EN","currency":"BWP","group":"","regions":[],"headerRegions":[]},
  {"name":"Brazīlija","code":"br","language":"PT","currency":"BRL","group":"Dienvidamerika","regions":["Sanpaulu","Rio de Žaneiro","Brazīlija","Minasa Žeraisa","Baija","Parana"],"headerRegions":["Sanpaulu","Rio de Žaneiro","Brazīlija","Minasa Žeraisa","Baija","Parana"]},
  {"name":"Bulgārija","code":"bg","language":"BG","currency":"EUR","group":"","regions":[],"headerRegions":[]},
  {"name":"Burkinafaso","code":"bf","language":"FR","currency":"XOF","group":"","regions":[],"headerRegions":[]},
  {"name":"Burundija","code":"bi","language":"FR","currency":"BIF","group":"","regions":[],"headerRegions":[]},
  {"name":"Centrālāfrikas Republika","code":"cf","language":"FR","currency":"XAF","group":"","regions":[],"headerRegions":[]},
  {"name":"Čada","code":"td","language":"FR","currency":"XAF","group":"","regions":[],"headerRegions":[]},
  {"name":"Čehija","code":"cz","language":"CS","currency":"CZK","group":"Eiropa","regions":["Prāga","Brno","Ostrava","Plzeņa","Bohēmija","Morāvija"],"headerRegions":["Prāga","Brno","Ostrava","Plzeņa","Bohēmija","Morāvija"]},
  {"name":"Čīle","code":"cl","language":"ES","currency":"CLP","group":"","regions":[],"headerRegions":[]},
  {"name":"Dānija","code":"dk","language":"DA","currency":"DKK","group":"Skandināvija","regions":["Kopenhāgena","Orhūsa","Odense","Olborka"],"headerRegions":["Kopenhāgena","Orhusa","Odense","Olborga","Zēlande","Jītlande"]},
  {"name":"Dienvidāfrikas Republika","code":"za","language":"EN","currency":"ZAR","group":"","regions":[],"headerRegions":[]},
  {"name":"Dienvidsudāna","code":"ss","language":"EN","currency":"SSP","group":"","regions":[],"headerRegions":[]},
  {"name":"Dominika","code":"dm","language":"EN","currency":"XCD","group":"","regions":[],"headerRegions":[]},
  {"name":"Dominikāna","code":"do","language":"ES","currency":"DOP","group":"","regions":[],"headerRegions":[]},
  {"name":"Džibutija","code":"dj","language":"FR","currency":"DJF","group":"","regions":[],"headerRegions":[]},
  {"name":"Ekvadora","code":"ec","language":"ES","currency":"USD","group":"","regions":[],"headerRegions":[]},
  {"name":"Ekvatoriālā Gvineja","code":"gq","language":"ES","currency":"XAF","group":"","regions":[],"headerRegions":[]},
  {"name":"Eritreja","code":"er","language":"EN","currency":"ERN","group":"","regions":[],"headerRegions":[]},
  {"name":"Etiopija","code":"et","language":"EN","currency":"ETB","group":"","regions":[],"headerRegions":[]},
  {"name":"Ēģipte","code":"eg","language":"EN","currency":"EGP","group":"","regions":[],"headerRegions":[]},
  {"name":"Fidži","code":"fj","language":"EN","currency":"FJD","group":"","regions":[],"headerRegions":[]},
  {"name":"Filipīnas","code":"ph","language":"EN","currency":"PHP","group":"","regions":[],"headerRegions":[]},
  {"name":"Francija","code":"fr","language":"FR","currency":"EUR","group":"Eiropa","regions":["Parīze","Marseļa","Liona","Tulūza","Nica","Nante"],"headerRegions":["Parīze","Marseļa","Liona","Tulūza","Nica","Nante","Bordo","Provansa","Korsika","Normandija"]},
  {"name":"Gabona","code":"ga","language":"FR","currency":"XAF","group":"","regions":[],"headerRegions":[]},
  {"name":"Gajāna","code":"gy","language":"EN","currency":"GYD","group":"","regions":[],"headerRegions":[]},
  {"name":"Gambija","code":"gm","language":"EN","currency":"GMD","group":"","regions":[],"headerRegions":[]},
  {"name":"Gana","code":"gh","language":"EN","currency":"GHS","group":"","regions":[],"headerRegions":[]},
  {"name":"Grenāda","code":"gd","language":"EN","currency":"XCD","group":"","regions":[],"headerRegions":[]},
  {"name":"Grieķija","code":"gr","language":"EL","currency":"EUR","group":"","regions":[],"headerRegions":[]},
  {"name":"Gvatemala","code":"gt","language":"ES","currency":"GTQ","group":"","regions":[],"headerRegions":[]},
  {"name":"Gvineja","code":"gn","language":"FR","currency":"GNF","group":"","regions":[],"headerRegions":[]},
  {"name":"Gvineja-Bisava","code":"gw","language":"PT","currency":"XOF","group":"","regions":[],"headerRegions":[]},
  {"name":"Haiti","code":"ht","language":"FR","currency":"HTG","group":"","regions":[],"headerRegions":[]},
  {"name":"Hondurasa","code":"hn","language":"ES","currency":"HNL","group":"","regions":[],"headerRegions":[]},
  {"name":"Horvātija","code":"hr","language":"EN","currency":"EUR","group":"","regions":[],"headerRegions":[]},
  {"name":"Igaunija","code":"ee","language":"EE","currency":"EUR","group":"Baltija","regions":["Tallina","Tartu","Narva","Pērnava","Kohtla-Järve"],"headerRegions":["Tallina","Tartu","Narva","Pērnava","Hāpsalu","Sāmsala","Hījumā","Viljandi"]},
  {"name":"Indija","code":"in","language":"EN","currency":"INR","group":"Āzija","regions":["Mumbaja","Deli","Bangalora","Goa","Haidarābāda","Čennai","Kolkata"],"headerRegions":["Mumbaja","Deli","Bangalora","Goa","Haidarābāda","Čennai","Kolkata"]},
  {"name":"Irāka","code":"iq","language":"EN","currency":"IQD","group":"","regions":[],"headerRegions":[]},
  {"name":"Islande","code":"is","language":"EN","currency":"ISK","group":"","regions":[],"headerRegions":[]},
  {"name":"Itālija","code":"it","language":"IT","currency":"EUR","group":"Eiropa","regions":["Roma","Milāna","Neapole","Turīna","Palermo","Florence"],"headerRegions":["Roma","Milāna","Neapole","Turīna","Sicīlija","Venēcija","Florence","Toskāna","Sardīnija","Kalabrija"]},
  {"name":"Izraēla","code":"il","language":"EN","currency":"ILS","group":"","regions":[],"headerRegions":[]},
  {"name":"Īrija","code":"ie","language":"EN","currency":"EUR","group":"","regions":[],"headerRegions":[]},
  {"name":"Jamaika","code":"jm","language":"EN","currency":"JMD","group":"","regions":[],"headerRegions":[]},
  {"name":"Jaunzēlande","code":"nz","language":"EN","currency":"NZD","group":"Okeānija","regions":["Oklanda","Velingtona","Kraistčērča","Hamiltona","Tauranga"],"headerRegions":["Oklanda","Velingtona","Kraistčērča","Hamiltona","Tauranga"]},
  {"name":"Jordānija","code":"jo","language":"EN","currency":"JOD","group":"","regions":[],"headerRegions":[]},
  {"name":"Kaboverde","code":"cv","language":"PT","currency":"CVE","group":"","regions":[],"headerRegions":[]},
  {"name":"Kamerūna","code":"cm","language":"FR","currency":"XAF","group":"","regions":[],"headerRegions":[]},
  {"name":"Kanāda","code":"ca","language":"EN","currency":"CAD","group":"Ziemeļamerika","regions":["Ontārio","Kvebeka","Britu Kolumbija","Alberta","Monreāla","Toronto"],"headerRegions":["Ontārio","Kvebeka","Britu Kolumbija","Alberta","Vankūvera","Toronto","Monreāla","Manitoba","Saskačevana","Jaunskotija"]},
  {"name":"Kazahstāna","code":"kz","language":"RU","currency":"KZT","group":"","regions":[],"headerRegions":[]},
  {"name":"Kenija","code":"ke","language":"EN","currency":"KES","group":"","regions":[],"headerRegions":[]},
  {"name":"Kipra","code":"cy","language":"EL","currency":"EUR","group":"","regions":[],"headerRegions":[]},
  {"name":"Kirgizstāna","code":"kg","language":"RU","currency":"KGS","group":"","regions":[],"headerRegions":[]},
  {"name":"Kiribati","code":"ki","language":"EN","currency":"AUD","group":"","regions":[],"headerRegions":[]},
  {"name":"Kolumbija","code":"co","language":"ES","currency":"COP","group":"","regions":[],"headerRegions":[]},
  {"name":"Komoru salas","code":"km","language":"FR","currency":"KMF","group":"","regions":[],"headerRegions":[]},
  {"name":"Kongo (Brazavila)","code":"cg","language":"FR","currency":"XAF","group":"","regions":[],"headerRegions":[]},
  {"name":"Kongo (Kinšasa)","code":"cd","language":"FR","currency":"CDF","group":"","regions":[],"headerRegions":[]},
  {"name":"Kostarika","code":"cr","language":"ES","currency":"CRC","group":"","regions":[],"headerRegions":[]},
  {"name":"Kotdivuāra","code":"ci","language":"FR","currency":"XOF","group":"","regions":[],"headerRegions":[]},
  {"name":"Krievija","code":"ru","language":"RU","currency":"RUB","group":"","regions":["Maskava","Sanktpēterburga","Novosibirska","Jekaterinburga","Kazaņa","Soči","Kaliningrada"],"headerRegions":["Maskava","Sanktpēterburga","Novosibirska","Jekaterinburga","Kazaņa","Soči","Kaliningrada"]},
  {"name":"Kuba","code":"cu","language":"ES","currency":"CUP","group":"","regions":[],"headerRegions":[]},
  {"name":"Lesoto","code":"ls","language":"EN","currency":"ZAR","group":"","regions":[],"headerRegions":[]},
  {"name":"Libāna","code":"lb","language":"EN","currency":"LBP","group":"","regions":[],"headerRegions":[]},
  {"name":"Libērija","code":"lr","language":"EN","currency":"LRD","group":"","regions":[],"headerRegions":[]},
  {"name":"Lielbritānija","code":"gb","language":"EN","currency":"GBP","group":"Eiropa","regions":["Londona","Mančestra","Birmingema","Liverpūle","Skotija","Velsa","Ziemeļīrija"],"headerRegions":["Londona","Mančestra","Birmingema","Skotija","Velsa","Ziemeļīrija","Liverpūle","Līdsā","Bristole","Glāzgova","Edinburga","Belfāsta"]},
  {"name":"Lietuva","code":"lt","language":"LT","currency":"EUR","group":"Baltija","regions":["Viļņa","Kauņa","Klaipēda","Šauļi","Panevēža","Alytus"],"headerRegions":["Viļņa","Kauņa","Klaipēda","Šauļi","Panevēža","Aukštaitija","Žemaitija","Dzūkija","Suvalkija"]},
  {"name":"Lihtenšteina","code":"li","language":"DE","currency":"CHF","group":"","regions":[],"headerRegions":[]},
  {"name":"Luksemburga","code":"lu","language":"FR","currency":"EUR","group":"","regions":[],"headerRegions":[]},
  {"name":"Madagaskara","code":"mg","language":"FR","currency":"MGA","group":"","regions":[],"headerRegions":[]},
  {"name":"Malaizija","code":"my","language":"EN","currency":"MYR","group":"","regions":[],"headerRegions":[]},
  {"name":"Malāvija","code":"mw","language":"EN","currency":"MWK","group":"","regions":[],"headerRegions":[]},
  {"name":"Maldīvija","code":"mv","language":"EN","currency":"MVR","group":"","regions":[],"headerRegions":[]},
  {"name":"Mali","code":"ml","language":"FR","currency":"XOF","group":"","regions":[],"headerRegions":[]},
  {"name":"Malta","code":"mt","language":"MT","currency":"EUR","group":"","regions":[],"headerRegions":[]},
  {"name":"Maroka","code":"ma","language":"FR","currency":"MAD","group":"","regions":[],"headerRegions":[]},
  {"name":"Maurīcija","code":"mu","language":"FR","currency":"MUR","group":"","regions":[],"headerRegions":[]},
  {"name":"Māršala salas","code":"mh","language":"EN","currency":"USD","group":"","regions":[],"headerRegions":[]},
  {"name":"Meksika","code":"mx","language":"ES","currency":"MXN","group":"Ziemeļamerika","regions":["Mehiko","Gvadalahara","Monterreja","Kankūna","Puebla","Halisko"],"headerRegions":["Mehiko","Gvadalahara","Monterreja","Kankūna","Puebla","Halisko"]},
  {"name":"Mikronēzija","code":"fm","language":"EN","currency":"USD","group":"","regions":[],"headerRegions":[]},
  {"name":"Moldova","code":"md","language":"RO","currency":"MDL","group":"","regions":[],"headerRegions":[]},
  {"name":"Monako","code":"mc","language":"FR","currency":"EUR","group":"","regions":[],"headerRegions":[]},
  {"name":"Mozambika","code":"mz","language":"PT","currency":"MZN","group":"","regions":[],"headerRegions":[]},
  {"name":"Namībija","code":"na","language":"EN","currency":"NAD","group":"","regions":[],"headerRegions":[]},
  {"name":"Nauru","code":"nr","language":"EN","currency":"AUD","group":"","regions":[],"headerRegions":[]},
  {"name":"Nigēra","code":"ne","language":"FR","currency":"XOF","group":"","regions":[],"headerRegions":[]},
  {"name":"Nigērija","code":"ng","language":"EN","currency":"NGN","group":"","regions":[],"headerRegions":[]},
  {"name":"Nikaragva","code":"ni","language":"ES","currency":"NIO","group":"","regions":[],"headerRegions":[]},
  {"name":"Nīderlande","code":"nl","language":"NL","currency":"EUR","group":"Eiropa","regions":["Amsterdama","Roterdama","Hāga","Utrehta","Eindhovena"],"headerRegions":["Amsterdama","Roterdama","Hāga","Utrehta","Eindhovena","Ziemeļholande","Dienvidholande"]},
  {"name":"Norvēģija","code":"no","language":"NO","currency":"NOK","group":"Skandināvija","regions":["Oslo","Bergena","Tronheima","Stavangere"],"headerRegions":["Oslo","Bergena","Tronheima","Stavangere","Ziemeļnorvēģija","Austrumorvēģija","Rietumorvēģija"]},
  {"name":"Pakistāna","code":"pk","language":"EN","currency":"PKR","group":"","regions":[],"headerRegions":[]},
  {"name":"Palau","code":"pw","language":"EN","currency":"USD","group":"","regions":[],"headerRegions":[]},
  {"name":"Panama","code":"pa","language":"ES","currency":"PAB","group":"","regions":[],"headerRegions":[]},
  {"name":"Papua-Jaungvineja","code":"pg","language":"EN","currency":"PGK","group":"","regions":[],"headerRegions":[]},
  {"name":"Paragvaja","code":"py","language":"ES","currency":"PYG","group":"","regions":[],"headerRegions":[]},
  {"name":"Peru","code":"pe","language":"ES","currency":"PEN","group":"","regions":[],"headerRegions":[]},
  {"name":"Polija","code":"pl","language":"PL","currency":"PLN","group":"Eiropa","regions":["Varšava","Krakova","Gdaņska","Poznaņa","Vroclava","Lodza"],"headerRegions":["Varšava","Krakova","Gdaņska","Vroclava","Poznaņa","Lodza","Silēzija","Mazovija","Mazpolija"]},
  {"name":"Portugāle","code":"pt","language":"PT","currency":"EUR","group":"","regions":[],"headerRegions":[]},
  {"name":"Ruanda","code":"rw","language":"EN","currency":"RWF","group":"","regions":[],"headerRegions":[]},
  {"name":"Rumānija","code":"ro","language":"RO","currency":"RON","group":"","regions":[],"headerRegions":[]},
  {"name":"Salvadora","code":"sv","language":"ES","currency":"USD","group":"","regions":[],"headerRegions":[]},
  {"name":"Samoa","code":"ws","language":"EN","currency":"WST","group":"","regions":[],"headerRegions":[]},
  {"name":"Sanmarīno","code":"sm","language":"IT","currency":"EUR","group":"","regions":[],"headerRegions":[]},
  {"name":"Santome un Prinsipi","code":"st","language":"PT","currency":"STN","group":"","regions":[],"headerRegions":[]},
  {"name":"Seišelu salas","code":"sc","language":"FR","currency":"SCR","group":"","regions":[],"headerRegions":[]},
  {"name":"Senegāla","code":"sn","language":"FR","currency":"XOF","group":"","regions":[],"headerRegions":[]},
  {"name":"Sentkitsa un Nevisa","code":"kn","language":"EN","currency":"XCD","group":"","regions":[],"headerRegions":[]},
  {"name":"Sentlūsija","code":"lc","language":"EN","currency":"XCD","group":"","regions":[],"headerRegions":[]},
  {"name":"Sentvinsenta un Grenadīnas","code":"vc","language":"EN","currency":"XCD","group":"","regions":[],"headerRegions":[]},
  {"name":"Singapūra","code":"sg","language":"EN","currency":"SGD","group":"","regions":[],"headerRegions":[]},
  {"name":"Sjerraleone","code":"sl","language":"EN","currency":"SLE","group":"","regions":[],"headerRegions":[]},
  {"name":"Slovākija","code":"sk","language":"SK","currency":"EUR","group":"","regions":[],"headerRegions":[]},
  {"name":"Slovēnija","code":"si","language":"SL","currency":"EUR","group":"","regions":[],"headerRegions":[]},
  {"name":"Somija","code":"fi","language":"FI","currency":"EUR","group":"Skandināvija","regions":["Helsinki","Espo","Tamperes","Vantaa","Oulu"],"headerRegions":["Helsinki","Espoo","Tampere","Turku","Lapzeme","Oulu","Ūsimā"]},
  {"name":"Spānija","code":"es","language":"ES","currency":"EUR","group":"Eiropa","regions":["Madride","Barselona","Valensija","Seviļa","Saragosa","Malaga"],"headerRegions":["Madride","Barselona","Valensija","Seviļa","Andalūzija","Katalonija","Malaga","Baleāru salas","Kanāriju salas"]},
  {"name":"Sudāna","code":"sd","language":"EN","currency":"SDG","group":"","regions":[],"headerRegions":[]},
  {"name":"Surinama","code":"sr","language":"NL","currency":"SRD","group":"","regions":[],"headerRegions":[]},
  {"name":"Svatini","code":"sz","language":"EN","currency":"SZL","group":"","regions":[],"headerRegions":[]},
  {"name":"Šveice","code":"ch","language":"DE","currency":"CHF","group":"Eiropa","regions":["Cīrihe","Ženēva","Bāzeli","Berne","Lozanna","Lucerna"],"headerRegions":["Cīrihe","Ženēva","Bāzeli","Berne","Lozanna","Lucerna"]},
  {"name":"Taizeme","code":"th","language":"EN","currency":"THB","group":"","regions":[],"headerRegions":[]},
  {"name":"Tanzānija","code":"tz","language":"EN","currency":"TZS","group":"","regions":[],"headerRegions":[]},
  {"name":"Togo","code":"tg","language":"FR","currency":"XOF","group":"","regions":[],"headerRegions":[]},
  {"name":"Tonga","code":"to","language":"EN","currency":"TOP","group":"","regions":[],"headerRegions":[]},
  {"name":"Trinidāda un Tobāgo","code":"tt","language":"EN","currency":"TTD","group":"","regions":[],"headerRegions":[]},
  {"name":"Tunisija","code":"tn","language":"FR","currency":"TND","group":"","regions":[],"headerRegions":[]},
  {"name":"Turcija","code":"tr","language":"TR","currency":"TRY","group":"Eirāzija","regions":["Stambula","Ankara","Antalja","Izmira","Bursa","Adana","Konja"],"headerRegions":["Stambula","Ankara","Antalja","Izmira","Bursa","Adana","Konja"]},
  {"name":"Tuvalu","code":"tv","language":"EN","currency":"AUD","group":"","regions":[],"headerRegions":[]},
  {"name":"Uganda","code":"ug","language":"EN","currency":"UGX","group":"","regions":[],"headerRegions":[]},
  {"name":"Ukraina","code":"ua","language":"RU","currency":"UAH","group":"Austrumeiropa","regions":["Kijiva","Ļviva","Odesa","Harkiva","Dnipro","Zaporižja","Krimas Autonomā Republika"],"headerRegions":["Kijiva","Ļviva","Odesa","Harkiva","Dnipro","Zaporižja","Krimas Autonomā Republika"]},
  {"name":"Ungārija","code":"hu","language":"HU","currency":"HUF","group":"","regions":[],"headerRegions":[]},
  {"name":"Urugvaja","code":"uy","language":"ES","currency":"UYU","group":"","regions":[],"headerRegions":[]},
  {"name":"Vanuatu","code":"vu","language":"EN","currency":"VUV","group":"","regions":[],"headerRegions":[]},
  {"name":"Vatikāns","code":"va","language":"IT","currency":"EUR","group":"","regions":[],"headerRegions":[]},
  {"name":"Vācija","code":"de","language":"DE","currency":"EUR","group":"Centrāleiropa","regions":["Bavārija (Bayern)","Bādene-Virtemberga (Baden-Württemberg)","Ziemeļreina-Vestfālene (Nordrhein-Westfalen)","Lejassaksija (Niedersachsen)","Hesene (Hessen)","Reinlande-Pfalca (Rheinland-Pfalz)","Saksija (Sachsen)","Tīringene (Thüringen)","Brandenburga (Brandenburg)","Saksija-Anhalte (Saksija-Anhalt)","Šlēsviga-Holšteina (Schleswig-Holstein)","Mēklenburga-Priekšpomerānija (Mecklenburg-Vorpommern)","Hamburga","Berlīne","Brēmene","Sārija (Saarland)","Minhene","Frankfurte pie Mainas","Ķelne","Štutgarte"],"headerRegions":["Berlīne","Minhene","Hamburga","Ķelne","Frankfurte pie Mainas","Štutgarte","Bādene-Virtemberga","Bavārija","Brandenburga","Brēmene","Hesene","Mēklenburga-Priekšpomerānija","Lejassaksija","Ziemeļreina-Vestfālene","Reina-Palatināte","Sāra","Saksija","Saksija-Anhalte","Šlēsviga-Holšteina","Tīringene"]},
  {"name":"Venecuēla","code":"ve","language":"ES","currency":"VES","group":"","regions":[],"headerRegions":[]},
  {"name":"Zambija","code":"zm","language":"EN","currency":"ZMW","group":"","regions":[],"headerRegions":[]},
  {"name":"Zālamana salas","code":"sb","language":"EN","currency":"SBD","group":"","regions":[],"headerRegions":[]},
  {"name":"Zimbabve","code":"zw","language":"EN","currency":"ZWG","group":"","regions":[],"headerRegions":[]},
  {"name":"Zviedrija","code":"se","language":"SV","currency":"SEK","group":"Skandināvija","regions":["Stokholma","Gēteborga","Malme","Uppsala"],"headerRegions":["Stokholma","Gēteborga","Malme","Upsala","Norlande","Svealande","Gētalande"]},
]

export const COUNTRIES: Country[] = countryData.map(country => ({
  ...country,
  flagUrl: `https://flagcdn.com/w40/${country.code}.png`,
}))

const aliases: Record<string, string> = {
  'Apvienotā Karaliste': 'gb',
  'ASV & Ziemeļamerika': 'us',
  'Koreja': 'kr',
  'Nīderlande': 'nl',
}

export function findCountry(value: string): Country | undefined {
  const name = value.trim().replace(/ \([A-Z]{3}\)$/, '')
  return COUNTRIES.find(country => country.name === name || country.code === aliases[name])
}

export function translatedCountryName(value: string, language: Language): string | undefined {
  const country = findCountry(value)
  if (!country) return undefined
  const locale = language === 'EE' ? 'et' : language === 'NO' ? 'nb' : language.toLowerCase()
  return new Intl.DisplayNames([locale], { type: 'region' }).of(country.code.toUpperCase())
}
